### ISSUE TITLE
Fix JDBC url on values

### ISSUE THREAD

**Issue by lucasmellos** [EugenMayer/helm-charts#25]
The values are shown that host property is required for database-secret, but host doesn't exists, instead jdbc does.
```yaml
- name: RUNDECK_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: "rundeck-database-secret"
                  key: jdbc
```

Original values
```yaml
database:
  # A secret including the following keys `type`,`host`,`port`,`user`,`password`,`database`
  # type can be postgresql/mysql and so forth. Should be in the same namespace as you deploy the helm chart
  secret_name: rundeck-database-secret
```

Should be
```yaml
database:
  # A secret including the following keys `type`,`jdbc`,`port`,`user`,`password`,`database`
  # type can be postgresql/mysql and so forth. Should be in the same namespace as you deploy the helm chart
  secret_name: rundeck-database-secret
```
