### ISSUE TITLE
Rundeck chart: sideCars value not applied in deployment template

### ISSUE THREAD

**Issue by jgtr-blis** [EugenMayer/helm-charts#50]
Contrary to the readme documentation (https://github.com/EugenMayer/helm-charts/tree/main/charts/rundeck#other-values) which states that the sideCars value "can be used to run additional containers in the pod" it appears that it isn't actually referenced in the templates so setting it's value doesn't do anything.

I believe this can be fixed by adding the following to the rundeck-backend-deployment.yaml template - I would have raised a PR, however I don't have permission to create a branch/PR on the repo:
```
             {{- toYaml .Values.resources | nindent 12 }}
+        {{- if .Values.sideCars }}
+          {{- toYaml .Values.sideCars | nindent 8 }}
+        {{- end }}
       {{- if .Values.nodeSelector }}
```

P.S. Thanks for your work on the Rundeck chart - as much as the documentation around Rundeck isn't great, as you stated, your chart certainly takes away some of the pain.

**Comment by EugenMayer** [comment]
Thank you for the kind words. Yes the entire situation around Rundeck looks rather dire, to be honest.

To be honest, i never planned to support side cars and rather would continue to do so by removing them from the readme (i removed them from the chart actively).

But feel free to convince me otherwise, what is you use case?

**Comment by jgtr-blis** [comment]
Happy new year! 
Thanks for the response - in my case I'm running the [rundeck-exporter](https://github.com/phsmith/rundeck_exporter) as a sidecar to export metrics to prometheus and the sidecar mechanism allows me to do this in a fairly clean way whereas alternatives approaches would be somewhat messy to manage (i.e. creating a custom version of the Rundeck docker image with the rundeck-exporter already installed and then passing the config values via the rundeck charts env variables section).


```
sideCars:
  - name: rundeck-exporter
    image: phsmith/rundeck-exporter:2.6.3
    env:
      - name: RUNDECK_EXPORTER_HOST
        value: 0.0.0.0
      - name: RUNDECK_EXPORTER_PORT
        value: "9100"
      - name: RUNDECK_URL
        value: http://127.0.0.1:4440
      - name: RUNDECK_CPU_STATS
        value: "true"
      - name: RUNDECK_MEMORY_STATS
        value: "true"
      - name: RUNDECK_PROJECTS_EXECUTIONS
        value: "true"
      - name: RUNDECK_EXPORTER_DEBUG
        value: "false"
      - name: RUNDECK_SKIP_SSL
        value: "true"
      - name: RUNDECK_API_VERSION
        value: "45"
    securityContext:
      runAsNonRoot: true
    ports:
      - containerPort: 9100
        name: metrics
        protocol: TCP

```

Out of curiosity what was the issue you encountered that made you take the decision to actively remove sidecars?
