### ISSUE TITLE
(Rundeck chart) Feature request: default admin secret

### ISSUE THREAD

**Issue by callen-rti** [EugenMayer/helm-charts#61]
I've been greatly enjoying the Rundeck chart, but the one thing that keeps it from being a simple install is the admin secret.

Currently this has to be created by the user, but I don't see why it couldn't be a "default", with the user/pass being "admin".

Something like this:
```
apiVersion: v1
kind: Secret
metadata:
  name: user-credentials-secret
type: Opaque
data:
  userCredentials: YWRtaW46YWRtaW4sdXNlcixhZG1pbixhcmNoaXRlY3QsZGVwbG95LGJ1aWxkCg==
```
